### ISSUE TITLE
rubidity idea / lang improvement proposal - Use Typed Classes for (Rubidity) Types (NOT Symbols)

### ISSUE THREAD

**Issue by geraldb** [0xFacet/facet-vm#51]
hello,

  here's a bigger idea / proposal on improving rubidity "classic" v2.  why not use typed classes for (rubidity types).  For example, `:address` becomes `Address`, `:uint256` becomes `UInt`, and so on.  See the [solidity-typed gem / library](https://www.rubydoc.info/gems/solidity-typed) for a 1:1 mapping of rubidity / solidity types to ruby typed classes.

Let's try to update  ERC20V2 syntax using typed classes  ( sorry for throwing in the "storage" proposal but otherwise unchanged ):

``` ruby
pragma :rubidity, "1.0.0"

contract :ERC20V2 do
  abstract

  event :Transfer, { from: Address, to: Address, amount: UInt }
  event :Approval, { owner: Address, spender: Address, amount: UInt }

  storage name: String,
          symbol: String,
          decimals: UInt,     # uint8
          totalSupply: UInt,
          balanceOf: Mapping( Address, UInt ),
          allowance: Mapping( Address, Mapping( Address, UInt ))


  constructor(name: String, symbol: String, decimals: UInt) {
    s.name = name
    s.symbol = symbol
    s.decimals = decimals
  }

  function :approve, { spender: Address, amount: UInt }, :virtual, returns: Bool do
    s.allowance[msg.sender][spender] = amount

    emit :Approval, owner: msg.sender, spender: spender, amount: amount

    return true
  end

  function :transfer, { to: Address, amount: UInt },  :virtual, returns: Bool do
    require(s.balanceOf[msg.sender] >= amount, 'Insufficient balance')

    s.balanceOf[msg.sender] -= amount
    s.balanceOf[to] += amount

    emit :Transfer, from: msg.sender, to: to, amount: amount

    return true
  end

  function :transferFrom, {
    from: Address,
    to: Address,
    amount: UInt
  }, :virtual, returns: Bool do
    allowed = s.allowance[from][msg.sender]

    require(s.balanceOf[from] >= amount, 'Insufficient balance')
    require(allowed >= amount, 'Insufficient allowance')

    s.allowance[from][msg.sender] = allowed - amount

    s.balanceOf[from] -= amount
    s.balanceOf[to] += amount

    emit :Transfer, from: from, to: to, amount: amount

    return true
  end

  function :_mint, { to: Address, amount: UInt }, :virtual do
    s.totalSupply += amount
    s.balanceOf[to] += amount

    emit :Transfer, from: address(0), to: to, amount: amount
  end

  function :_burn, { from: Address, amount: UInt }, :virtual do
    s.balanceOf[from] -= amount
    s.totalSupply -= amount

    emit :Transfer, from: from, to: address(0), amount: amount
  end
end
```

If i dare to say the difference is not only in syntax but also leading to more solid code because the typed classes are real types NOT symbols to state the obvious ;-).  Anyways, keep up the great work on rubidity.  If anyone wants to comment happy to hear what i am missing or not seeing (when using typed classes).

**Comment by RogerPodacter** [comment]
Symbols are definitely not ideal, but if we use constants that could lead to ambiguity if someone wants to give a contract (or library / interface) the same name as a type.

A real life example would be OpenZeppelin's `Address` library.

Contracts are worse because contracts are themselves types, so you need to make sure `Address(this)` unambiguous about whether you're casting `this` as an `address` or as an `Address` contract.

I think probably best to leave things as they are until we can figure out the first-best solution of using lowercase words without the `:` as in `function :_burn, { from: address, amount: uint }`. I just wish `uint[]` was valid Ruby!

Thoughts?

**Comment by geraldb** [comment]
Thanks for the comments and taking the time.  Good points.

To keep things simple and managable I would use the (built-in) constant rules of ruby itself as a rule. If there's a conflict like calling a contract Array than you have to rename to MyArray or Contract::Array ;-) or something. Same with Address. You cannot use Address for a contract name; use MyAddress or Zeppelin:: Address or such.

 > I just wish uint[] was valid Ruby!

Well, if i dare to say if it is Rubidity (and Ruby hosted)  I would follow the Ruby rules with Types being Uppercase and again reuse the built-in ruby machinery (with the result of way faster, more robust, etc.) - rebuilding all the method lookups and inheritance and  so on i think will "not scale" - why not trust into 25+ years of production use that ruby has accumulated?   

but yes - i see your point about the ugly array syntax with classes e.g. Array( UInt, 5 ).new instead of uint[5] or such.

One "hack" is to preprocess the source before handing over to ruby than you can use all lowercase types - but than again the question is what "format" to use for the preprocessed source - and again if would suggest that in the long run it will be easier  with ruby in ruby.  

Anyways, keep doing / using what you think is best.     I try to work on a "classic" version with function-style contract methods in the next days (but still with "typed classes" for types)  to experiment.    Keep up the great work and sorry for taking up your time.

**Comment by RogerPodacter** [comment]
Thinking more I'm not sure `function :_burn, { from: address, amount: uint }` actually looks good. It's kind of an "uncanny valley" of being not quite Solidity and also not quite Ruby.

Overall I think it's more important to track Solidity than it is to track Ruby because one of my big goals is a language that someone can port from Solidity line-by-line with having to understand as few new things as possible. But if you can't track Solidity you might as well track Ruby.

I don't think it's quite right say that in Ruby types are uppercase because `Array` etc are classes, not types, and so I think the "correct" Ruby way to implement what we want would be a class called like `IntegerArrayWithDefault` which would include `Enumerable`, not even inheriting from array. Using `Array` with non-standard typing functionality would be confusing to a pure Rubist IMO.

Not that I think this is such a big deal, my bigger issue would be the type-contract ambiguity.

Anyway as you mention I don't think it's realistic to expect us to be able to get everything we need out of Rubidity purely through runtime evaluation of "normal" code.

As an example, if we want to say `ERC20._mint()` in a child contract, that is basically not possible using Ruby without some truly hack-y `const_missing` stuff, and this is a core part of Solidity syntax.

This is not to mention preserving security and tracking gas expense, which is not an immediate concern but cannot be counted out by anything we do now.

I am working on a hopefully general solution here using the `parser` and `unparser` gems. Here's a test where I'm replacing `ERC20._mint()` with `this.ERC20._mint()`:

```ruby
class ContractReplacer
  include AST::Processor::Mixin

  def initialize(parent_contracts)
    @parent_contracts = parent_contracts.map(&:to_sym)
  end
  
  def s(type, *children)
    Parser::AST::Node.new(type, children)
  end
  
  def handler_missing(node)
    new_kids = node.children.map do |child|
      if child.respond_to?(:to_ast)
        child.updated(nil, process(child), nil)
      else
        child
      end
    end
    
    node.updated(nil, new_kids.flatten, nil)
  end
  
  def on_send(node)
    receiver, method_name, *args = *node
    
    return node unless receiver&.type == :const
    
    parent, name = *receiver
    
    unless parent.nil? && @parent_contracts.include?(name)
      return node
    end
    
    s(:send,
      s(:send,
        s(:send, nil, :this), name), method_name, *args)
  end
end
```

**Comment by geraldb** [comment]
Wow. As always thanks for taking the time. Really appreciate the detailed answers and real-world examples. Keep going.   Even if we disagree on the style (that really doesn't matter) and what not to love - if you have two options - classic (more solidity-ish) and "alternate" (more ruby-ish). 

About:

> As an example, if we want to say ERC20._mint() in a child contract, that is basically not possible using Ruby without some truly hack-y const_missing stuff, and this is a core part of Solidity syntax.

Not sure i understand what is the limitation and why it cannot work in ruby.  In the "alternate" rubidity i generate typed (public) wrapper methods for the "unsafe / untyped" version AND every method gets two versions one with namespace (incl. contract name) and one replacing the "untyped", thus, `ERC20._mint()` becomes `ERC20#__ERC20___mint()` and `ERC20#_mint()` and `ERC20#_mint()` becomes `ERC20#_mint_unsafe()`.   anyways, all i am trying to say is that if you want to call a specific "super" class method up the inheritance tree than you can use the "long" form e.g.  __ERC20___mint() or yes, because it is ruby you can also use simply `super`  and get the (super) method if overriden!  

Again sorry for taking up your time. Keep going. Love the (real-world) contract example driven approach.  I try to "convert" as many contracts as i can to show that there are no limitation with the "more ruby-ish" version BUT sure sometimes the syntax changes (a little).

**Comment by geraldb** [comment]
PS:

> I don't think it's quite right say that in Ruby types are uppercase because Array etc are classes, not types, and so I think the "correct" Ruby way to implement what we want would be a class called like IntegerArrayWithDefault which would include Enumerable, not even inheriting from array. Using Array with non-standard typing functionality would be confusing to a pure Rubist IMO.

Allow me to comment on the typed classes.  In ruby a class is really a type e.g. obj.class is bascially getting the type (and class being the "object-oriented" ruby name for type), thus, the String class is the String type, the Array class is the Array type and so on.    Anyways, i don't care really about semantics / hair splitting about words.

The point is:  Yes, believe it or not - the "more ruby-ish" rubidity IS using what you state is confusing to a pure rubyist.   it IS using its own String class (Types::String) that has NO relation to ::String (no inheritance), same with the Array class (Types::Array) that is really a factory (that is, class builder)!  If you use Types::Array.new( String ), that you get a class, that is, a typed (dynamic) array for string (and strings being Types::String) and so on.    If I dare to say - this model of using your own types / classes works like a charm - no method_missing or whatever - the only downside is really that "no magic" you have to code everything and cannot "magically" delegate or forward with "method_missing" and hope that this will somehow work out.     

PS:  The rubidity-typed gem with the typed classes is now known as the [solidity-typed gem](https://rubygems.org/gems/solidity-typed) (to highlight that the types incl. string, array, struct, etc. are not ruby but solidity types) and all have the "magic" zero machinery.
